version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd
      MYSQL_USER: aurora_user
      MYSQL_PASSWORD: aurora_user_password
      MYSQL_DATABASE: aurora

  spring-boot-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8181:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/aurora
      SPRING_DATASOURCE_USERNAME: aurora_user
      SPRING_DATASOURCE_PASSWORD: aurora_user_password

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
